### ISSUE TITLE
Function read should return -1 in case of error, then byte_read SHOULD'T be an unsigned int, since it can take a negative value....

### ISSUE THREAD

**Issue by pulgamecanica** [Caceresenzo/My-School-42-Piscine-Experience#5]
https://github.com/Caceresenzo/My-School-42-Piscine-Experience/blob/4115c5d0a17a94f8ea9b8c1c4b017612c6838bfd/day12:%20C%20Piscine%20C%2010/ex01/srcs/cat.c#L38

**Comment by Caceresenzo** [comment]
I wrote this code more than 2 years ago.
I was still learning and for this particular project I was trying to finish as fast as I can since the final exam was the next day.

But yes you are right, it should have been an signed type. A `long` or even better, the `ssize_t` would have been the best choice.
